import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {prepareChatBackground} from '@/lib/chatBackground';
export function ChatBackgroundDialog({open,onOpenChange,url,onSave,loadError}:{open:boolean;onOpenChange:(open:boolean)=>void;url:string;onSave:(blob:Blob|null)=>Promise<void>;loadError?:string}){
 const [draft,setDraft]=useState<Blob|null|undefined>();const [preview,setPreview]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const file=useRef<HTMLInputElement>(null);const mounted=useRef(true);const selection=useRef(0);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;selection.current++}},[]);
 useEffect(()=>{selection.current++;setDraft(undefined);setError('');},[open]);
 useEffect(()=>{const next=draft?URL.createObjectURL(draft):'';setPreview(next);return()=>{if(next)URL.revokeObjectURL(next)}},[draft]);
 const choose=async(chosen:File)=>{const token=++selection.current;setBusy(true);setError('');try{const blob=await prepareChatBackground(chosen);if(mounted.current&&token===selection.current)setDraft(blob);}catch(e){if(mounted.current&&token===selection.current)setError(e instanceof Error?e.message:'画像を読み込めませんでした');}finally{if(mounted.current)setBusy(false)}};
 const save=async()=>{if(draft===undefined)return;setBusy(true);setError('');try{await onSave(draft);if(mounted.current)onOpenChange(false);}catch{if(mounted.current)setError('背景を保存できませんでした。端末の空き容量などを確認してください。');}finally{if(mounted.current)setBusy(false)}};
 const shown=draft===undefined?url:preview;
 return <Dialog open={open} onOpenChange={next=>{if(!busy)onOpenChange(next)}}><DialogContent className="dm-dialog dm-background-dialog"><DialogTitle>チャットの背景</DialogTitle><DialogDescription>この会話の背景を設定します。自分のこの端末にだけ保存され、相手には表示されません。</DialogDescription><div className="dm-background-preview" style={shown?{backgroundImage:`url(${JSON.stringify(shown)})`}:undefined}>{!shown&&<span>背景なし</span>}</div><input ref={file} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/avif" onChange={e=>{const selected=e.target.files?.[0];e.target.value='';if(selected)void choose(selected)}}/><button className="dm-secondary" type="button" disabled={busy} onClick={()=>file.current?.click()}>画像を選択</button><button className="dm-secondary" type="button" disabled={busy||(!url&&!draft)} onClick={()=>setDraft(null)}>背景を解除</button>{(error||loadError)&&<p className="dm-error" role="alert">{error||loadError}</p>}<div className="dm-delete-controls"><button className="dm-secondary" type="button" disabled={busy} onClick={()=>onOpenChange(false)}>キャンセル</button><button className="dm-primary" type="button" disabled={busy||draft===undefined} onClick={()=>void save()}>{busy?'処理中…':'保存'}</button></div></DialogContent></Dialog>;
}
