import {handleDirectMedia} from './index.ts';
const actor='11111111-1111-4111-8111-111111111111',peer='22222222-2222-4222-8222-222222222222',conversation='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',message='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
for(const [key,value]of Object.entries({SUPABASE_URL:'https://db.test',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service',CLOUDINARY_CLOUD_NAME:'cloud',CLOUDINARY_API_KEY:'key',CLOUDINARY_API_SECRET:'secret'}))Deno.env.set(key,value);
const json=(data:unknown)=>Response.json(data);
async function mocked(run:()=>Promise<void>,handler:(url:URL,init?:RequestInit)=>Response|Promise<Response>){const original=globalThis.fetch;globalThis.fetch=((input:Request|string|URL,init?:RequestInit)=>{const url=new URL(input instanceof Request?input.url:String(input));if(url.pathname==='/auth/v1/user')return Promise.resolve(json({id:actor}));if(url.pathname.endsWith('/consume_security_quota'))return Promise.resolve(json(true));return Promise.resolve(handler(url,init));}) as typeof fetch;try{await run();}finally{globalThis.fetch=original;}}
const upload=()=>{const body=new FormData();body.set('conversationId',conversation);body.set('file',new File(['png'],'a.png',{type:'image/png'}));return new Request('https://edge.test',{method:'POST',headers:{authorization:'Bearer test'},body});};
Deno.test('nonparticipant cannot upload a Cloudinary asset',()=>mocked(async()=>{const response=await handleDirectMedia(upload());if(response.status!==403)throw Error(String(response.status));},url=>{if(url.pathname.endsWith('/direct_conversations'))return json({user_low:peer,user_high:peer,status:'accepted'});throw Error('Unexpected provider access');}));
Deno.test('uploads authenticated Cloudinary media and registers only the server-generated reference',()=>{let ref='';return mocked(async()=>{const response=await handleDirectMedia(upload());const result=await response.json();if(response.status!==200||result.ref!==ref||!ref.startsWith(`cloudinary:direct_messages/${conversation}/${actor}/`))throw Error(JSON.stringify(result));},(url,init)=>{if(url.pathname.endsWith('/direct_conversations'))return json({user_low:actor,user_high:peer,status:'accepted'});if(url.pathname.endsWith('/image/upload')){const body=init?.body as FormData;if(body.get('type')!=='authenticated'||!body.get('signature'))throw Error('Unprotected media');const id=String(body.get('public_id'));ref=`cloudinary:${id}`;return json({public_id:id,type:'authenticated',format:'png'});}if(url.pathname.endsWith('/register_direct_media')){const body=JSON.parse(String(init?.body));if(body.ref!==ref||body.actor!==actor)throw Error('Invalid registration');return json(null);}throw Error(url.pathname);});});
Deno.test('read cannot bypass the viewer message policy',()=>mocked(async()=>{const response=await handleDirectMedia(new Request('https://edge.test',{method:'POST',headers:{authorization:'Bearer test','content-type':'application/json'},body:JSON.stringify({action:'read',messageIds:[message]})}));if(response.status!==403)throw Error(String(response.status));},url=>{if(url.pathname.endsWith('/direct_messages'))return json([]);throw Error('Unexpected signing access');}));
Deno.test('read returns an expiring signed URL for visible messages',()=>{const ref=`cloudinary:direct_messages/${conversation}/${actor}/cccccccc-cccc-4ccc-8ccc-cccccccccccc`;return mocked(async()=>{const response=await handleDirectMedia(new Request('https://edge.test',{method:'POST',headers:{authorization:'Bearer test','content-type':'application/json'},body:JSON.stringify({action:'read',messageIds:[message]})}));const body=await response.json();if(response.status!==200)throw Error(JSON.stringify(body));const url=new URL(body.urls[ref]);if(url.searchParams.get('type')!=='authenticated'||!url.searchParams.get('expires_at')||!url.searchParams.get('signature'))throw Error('Unsigned asset');},url=>{if(url.pathname.endsWith('/direct_messages'))return json([{id:message,conversation_id:conversation,attachments:[ref]}]);if(url.pathname.endsWith('/direct_conversations'))return json([{id:conversation,media_assets:{[ref]:{owner:actor,format:'png'}}}]);throw Error(url.pathname);});});
