import {ChatMenuContent} from '@/components/ai/ChatMenuContent';
import { AI_CHAT_DELETED, AI_CHAT_HISTORY_CHANGED, AI_FRIENDS_CHANGED, listAssistants, loadAvatars, avatarOf } from '@/lib/aiFriends';
import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {Link,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {useInfiniteQuery,useQuery,useQueryClient} from '@tanstack/react-query';
import {Pencil,Pin,PinOff,Trash2,ArrowDown,Check,CheckCheck,ChevronDown,Link2,Loader2,Lock,MessageCircle,MessageCirclePlus,MoreHorizontal,Plus,Search,Send,Settings,X} from 'lucide-react';
import {useAuth} from '@/hooks/useAuth';
import {supabase} from '@/lib/supabase';
import {DirectMessagePanelHeader} from '@/components/layout/Header';
import {PrivateAccountBadge} from '@/components/common/PrivateAccountBadge';
import {Avatar,AvatarFallback,AvatarImage} from '@/components/ui/avatar';
import {Skeleton} from '@/components/ui/skeleton';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {DropdownMenu,DropdownMenuItem,DropdownMenuSeparator,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {deleteDirectChat,getChatInboxPreferences,setChatInboxPreference,discardDirectMedia,directKeys,getDirectInbox,getDirectMessages,getDirectPreferences,openDirectConversation,readDirectConversation,respondDirectRequest,searchDirectPeers,sendDirectMessage,setDirectPreferences,uploadDirectMedia,type DirectConversation,type DirectPeer} from '@/api/directMessages';
import './direct-messages.css';
const LimeAIChat = lazy(() => import('./ChatPage'));
const limeAI = {id:'limeai',username:'LimeAI',displayName:'LimeAI',avatarUrl:`${import.meta.env.BASE_URL}pwa-192x192.png`,createdAt:''};

function ConversationRow({id,peer,preview,updatedAt,unread=0,active,pinned,onOpen,onPin,onDelete,onEdit}:{id:string;peer:DirectPeer;preview:string;updatedAt?:string;unread?:number;active:boolean;pinned:boolean;onOpen:()=>void;onPin:()=>void;onDelete?:()=>void;onEdit?:()=>void}){
 const [open,setOpen]=useState(false);const row=useRef<HTMLButtonElement>(null);const hold=useRef<ReturnType<typeof setTimeout>>();const origin=useRef({x:0,y:0});const held=useRef(false);
 const cancel=()=>{clearTimeout(hold.current);hold.current=undefined;};useEffect(()=>()=>clearTimeout(hold.current),[]);
 return <DropdownMenu open={open} onOpenChange={setOpen} modal={false}><div className="dm-conversation-row" data-chat-id={id}>
  <DropdownMenuTrigger className="dm-row-anchor" tabIndex={-1} aria-hidden="true"/>
  <button ref={row} type="button" className={`dm-conversation ${active?'is-active':''}`} aria-current={active?'true':undefined}
   onPointerDown={event=>{held.current=false;origin.current={x:event.clientX,y:event.clientY};if(event.pointerType!=='mouse'){hold.current=setTimeout(()=>{held.current=true;setOpen(true);},500);}}}
   onPointerMove={event=>{if(Math.hypot(event.clientX-origin.current.x,event.clientY-origin.current.y)>10)cancel();}} onPointerUp={cancel} onPointerCancel={cancel}
   onContextMenu={event=>{event.preventDefault();cancel();held.current=true;setOpen(true)}}
   onClick={()=>{if(held.current){held.current=false;return;}setOpen(false);onOpen();}}>
   <PeerAvatar peer={peer}/><span className="dm-conversation-text"><span className="dm-conversation-top"><PeerName peer={peer}/>{updatedAt&&<time>{shortTime(updatedAt)}</time>}{pinned&&<Pin size={14} className="dm-pinned" aria-label="固定済み"/>}</span><span className="dm-preview">{preview}</span></span>{unread>0&&<span className="dm-unread">{unread>99?'99+':unread}</span>}
  </button>
 </div>{open&&<ChatMenuContent onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();setOpen(false);}}} align="end" side="bottom" className="dm-menu dm-conversation-menu" onCloseAutoFocus={event=>{event.preventDefault();row.current?.focus({preventScroll:true});}}>
  <DropdownMenuItem onSelect={onPin}>{pinned?<PinOff size={21}/>:<Pin size={21}/>}チャットを{pinned?'固定解除':'固定'}</DropdownMenuItem>
  {onEdit&&<DropdownMenuItem onSelect={onEdit}><Pencil size={21}/>フレンドを編集</DropdownMenuItem>}
  {onDelete&&<DropdownMenuItem className="dm-delete-item" onSelect={onDelete}><Trash2 size={21}/>チャットを削除</DropdownMenuItem>}
 </ChatMenuContent>}</DropdownMenu>;
}

function PeerAvatar({peer,className=''}:{peer:DirectPeer;className?:string}){return <Avatar className={`dm-avatar ${className}`}><AvatarImage src={peer.avatarUrl||undefined}/><AvatarFallback>{peer.displayName?.[0]||peer.username[0]}</AvatarFallback></Avatar>;}
function PeerName({peer}:{peer:DirectPeer}){return <span className="dm-peer-name">{peer.displayName}{peer.isPrivate&&<PrivateAccountBadge className="h-4 w-4"/>}{peer.isOfficial&&<img src={`${import.meta.env.BASE_URL}verified.png`} alt="認証済み" className="h-4 w-4"/>}</span>;}
function messageText(content:string){
 if(/^https?:\/\/[^\s]+$/.test(content.trim())){try{const url=new URL(content.trim());return <a className="dm-link-card" href={url.href} target="_blank" rel="noopener noreferrer"><span className="dm-link-icon"><Link2 size={24}/></span><span><strong>{content}</strong><span>{url.hostname}</span></span></a>;}catch{/* Fall through to text when the URL is incomplete. */}}
 return content.split(/(https?:\/\/[^\s]+)/g).map((part,i)=>/^https?:\/\//.test(part)?<a key={i} href={part} target="_blank" rel="noopener noreferrer">{part}</a>:part);
}
function shortTime(value:string){return new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric'}).format(new Date(value));}
const errorText=(error:unknown)=>error instanceof Error?error.message:typeof error==='object'&&error&&'message' in error?String(error.message):'処理に失敗しました。もう一度お試しください';
export default function DirectMessages(){
 const {user}=useAuth();const {conversationId}=useParams();const navigate=useNavigate();const [searchParams]=useSearchParams();const friendId=conversationId?.startsWith('friend:')?conversationId.slice(7):undefined;const isAI=conversationId==='limeai'||!!friendId;const client=useQueryClient();
 const [filter,setFilter]=useState<'all'|'unread'|'requests'>('all');const [search,setSearch]=useState('');const [newChat,setNewChat]=useState(false);const [peerSearch,setPeerSearch]=useState('');const [debouncedSearch,setDebouncedSearch]=useState('');
 const [settings,setSettings]=useState(false);const [preferenceDialog,setPreferenceDialog]=useState(false);const [preferenceDraft,setPreferenceDraft]=useState<'everyone'|'none'>('everyone');const [details,setDetails]=useState(false);
 const [draftPeer,setDraftPeer]=useState<DirectPeer|null>(null);const [content,setContent]=useState('');const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [newMessageBelow,setNewMessageBelow]=useState(false);
 const selectedConversation=useRef(conversationId);selectedConversation.current=conversationId;
 const [friendRevision,setFriendRevision]=useState(0);
 useEffect(()=>{const refresh=()=>setFriendRevision(value=>value+1);window.addEventListener(AI_FRIENDS_CHANGED,refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener(AI_FRIENDS_CHANGED,refresh);window.removeEventListener('storage',refresh)}},[]);
 const friends=useMemo(()=>listAssistants(user?.id).map(friend=>({friend,peer:{id:friend.id,username:friend.name,displayName:friend.name,avatarUrl:avatarOf(friend,loadAvatars(user?.id)),createdAt:''}})),[user?.id,friendRevision]);
 const workspace=useRef<HTMLDivElement>(null);
 const bottom=useRef<HTMLDivElement>(null);const scroller=useRef<HTMLDivElement>(null);const fileInput=useRef<HTMLInputElement>(null);const historyTop=useRef<HTMLDivElement>(null);const nearBottom=useRef(true);const readThrough=useRef('');
 useEffect(()=>{const viewport=window.visualViewport;if(!viewport)return;const update=()=>workspace.current?.style.setProperty('--dm-viewport-height',`${viewport.height}px`);update();viewport.addEventListener('resize',update);return()=>viewport.removeEventListener('resize',update);},[]);
 const chatPreferences=useQuery({queryKey:['chat-inbox-preferences',user?.id],queryFn:getChatInboxPreferences,enabled:!!user});
 const [deleteTarget,setDeleteTarget]=useState<{id:string;name:string}|null>(null);
 const inbox=useQuery({queryKey:[...directKeys.inbox,user?.id],queryFn:getDirectInbox,enabled:!!user});
 const aiHistory=useQuery({queryKey:['ai-inbox-history',user?.id],enabled:!!user,queryFn:async()=>{const {data,error}=await supabase.from('chat_sessions').select('id,messages,updated_at').eq('user_id',user!.id).order('updated_at',{ascending:false});if(error)throw error;return data??[];}});
 useEffect(()=>{const refresh=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.uid===user?.id&&detail.session){client.setQueryData(['ai-inbox-history',user?.id],(rows:typeof aiHistory.data)=>[detail.session,...(rows??[]).filter(row=>row.id!==detail.session.id)]);}else{setFriendRevision(value=>value+1);void client.invalidateQueries({queryKey:['ai-inbox-history',user?.id]});}};window.addEventListener(AI_CHAT_HISTORY_CHANGED,refresh);return()=>window.removeEventListener(AI_CHAT_HISTORY_CHANGED,refresh);},[client,user?.id]);
 const aiPreviews=useMemo(()=>{let meta:Record<string,{assistantId?:string}>={};try{meta=JSON.parse(localStorage.getItem(`limeai:${user?.id||'guest'}:session-meta`)??'{}')}catch{}const result:Record<string,string>={};for(const session of [...(aiHistory.data??[])].sort((a,b)=>new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime())){const key=meta[session.id]?.assistantId??'limeai';if(key in result)continue;const messages=Array.isArray(session.messages)?session.messages:[];const last=[...messages].reverse().find(message=>typeof message.content==='string'&&message.content.trim());if(last)result[key]=last.content;}return result;},[aiHistory.data,user?.id,friendRevision]);
 const preferences=useQuery({queryKey:[...directKeys.preferences,user?.id],queryFn:getDirectPreferences,enabled:!!user});
 const conversation=useQuery({queryKey:['direct-conversation',conversationId,user?.id],enabled:!!conversationId&&!isAI&&!!user,queryFn:async()=>{
  const {data:c,error:e}=await supabase.from('direct_conversations').select('*').eq('id',conversationId!).single();if(e)throw e;
  const {data:p,error:pe}=await supabase.from('profiles').select('id,username,display_name,avatar_url,is_private,is_official,created_at').eq('id',c.user_low===user!.id?c.user_high:c.user_low).single();if(pe)throw pe;
  return {id:c.id,status:c.status,initiatedBy:c.initiated_by,peer:{id:p.id,username:p.username,displayName:p.display_name||p.username,avatarUrl:p.avatar_url||'',isPrivate:p.is_private,isOfficial:p.is_official,createdAt:p.created_at}} as DirectConversation;
 }});
 const active=inbox.data?.find(c=>c.id===conversationId)??conversation.data;
 const peer=active?.peer??draftPeer;
 const messages=useInfiniteQuery({queryKey:[...directKeys.messages(conversationId??''),user?.id],enabled:!!conversationId&&!isAI&&!!user&&active?.status!=='declined',initialPageParam:undefined as {created_at:string;id:string}|undefined,queryFn:({pageParam})=>getDirectMessages(conversationId!,pageParam),getNextPageParam:last=>last.length===50?{id:last[last.length-1].id,created_at:last[last.length-1].created_at}:undefined});
 const chronological=useMemo(()=>[...new Map((messages.data?.pages.flat()??[]).map(m=>[m.id,m])).values()].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id)),[messages.data]);
 const last=chronological[chronological.length-1];
 const incoming=active?.status==='pending'&&active.initiatedBy!==user?.id;
 const canSend=!!peer&&active?.status!=='declined'&&!incoming&&(active?.status!=='pending'||chronological.length===0);
 const requestCount=(inbox.data??[]).filter(c=>c.status==='pending'&&c.initiatedBy!==user?.id).length;
 const showLimeAI=filter==='all'&&'limeai'.includes(search.toLowerCase());
 const visibleFriends=filter==='all'?friends.filter(({friend})=>!chatPreferences.data?.hidden?.[`friend:${friend.id}`]&&`${friend.name} ${friend.description}`.toLowerCase().includes(search.toLowerCase())):[];
 const filtered=(inbox.data??[]).filter(c=>(filter!=='requests'||c.status==='pending'&&c.initiatedBy!==user?.id)&&(filter!=='unread'||c.unreadCount>0)&&`${c.peer.displayName} ${c.peer.username} ${c.preview}`.toLowerCase().includes(search.toLowerCase()));
 useEffect(()=>{const timer=setTimeout(()=>setDebouncedSearch(peerSearch),250);return()=>clearTimeout(timer);},[peerSearch]);
 const peers=useQuery({queryKey:['direct-peer-search',debouncedSearch],queryFn:()=>searchDirectPeers(debouncedSearch),enabled:newChat&&debouncedSearch.trim().length>0});
 useEffect(()=>{if(!conversationId)setDraftPeer(null);setContent('');setFiles([]);setError('');setDetails(false);setNewMessageBelow(false);nearBottom.current=true;readThrough.current='';},[conversationId]);
 useEffect(()=>{if(!user)return;const channel=supabase.channel(`direct-workspace-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'direct_conversations'},()=>{void client.invalidateQueries({queryKey:directKeys.inbox});void client.invalidateQueries({queryKey:['direct-conversation']});}).on('postgres_changes',{event:'INSERT',schema:'public',table:'direct_messages'},payload=>{void client.invalidateQueries({queryKey:directKeys.inbox});const id=payload.new.conversation_id;if(id===conversationId)void client.invalidateQueries({queryKey:directKeys.messages(id)});}).subscribe();
  const refresh=()=>{if(document.visibilityState==='visible'){void client.invalidateQueries({queryKey:directKeys.inbox});if(conversationId&&!isAI)void client.invalidateQueries({queryKey:directKeys.messages(conversationId)});}};document.addEventListener('visibilitychange',refresh);window.addEventListener('online',refresh);
  return()=>{void supabase.removeChannel(channel);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('online',refresh);};
 },[user?.id,conversationId,client]);
 const markRead=()=>{if(!conversationId||!last||document.visibilityState!=='visible'||!nearBottom.current||readThrough.current===last.created_at)return;readThrough.current=last.created_at;void readDirectConversation(conversationId,last.created_at).then(()=>client.invalidateQueries({queryKey:directKeys.inbox})).catch(()=>{readThrough.current='';});};
 useEffect(()=>{const visible=()=>{if(document.visibilityState==='visible')markRead();};document.addEventListener('visibilitychange',visible);return()=>document.removeEventListener('visibilitychange',visible);},[last?.created_at,conversationId]);
 useEffect(()=>{if(!last)return;if(nearBottom.current){bottom.current?.scrollIntoView({block:'end',behavior:'auto'});markRead();}else setNewMessageBelow(true);},[last?.id,conversationId]);
 useEffect(()=>{const el=historyTop.current;if(!el||!messages.hasNextPage)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&!messages.isFetchingNextPage){const height=scroller.current?.scrollHeight??0;void messages.fetchNextPage().then(()=>requestAnimationFrame(()=>{if(scroller.current)scroller.current.scrollTop+=scroller.current.scrollHeight-height;}));}},{root:scroller.current,rootMargin:'80px'});observer.observe(el);return()=>observer.disconnect();},[messages.hasNextPage,messages.isFetchingNextPage,conversationId]);
 const [previews,setPreviews]=useState<string[]>([]);useEffect(()=>{const urls=files.map(file=>URL.createObjectURL(file));setPreviews(urls);return()=>urls.forEach(url=>URL.revokeObjectURL(url));},[files]);
 const run=async(action:()=>Promise<void>)=>{setError('');setBusy(true);try{await action();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const pickPeer=(chosen:DirectPeer)=>void run(async()=>{const id=await openDirectConversation(chosen.id);setDraftPeer(chosen);setNewChat(false);setPeerSearch('');setSettings(false);navigate(`/messages/${id}`);void client.invalidateQueries({queryKey:['direct-conversation',id]});});
 const send=()=>{if(!peer||!canSend||busy||(!content.trim()&&!files.length))return;const recipient=peer;const currentId=conversationId;const body=content.trim();const attachments=files;void run(async()=>{
  const id=currentId??await openDirectConversation(recipient.id);const paths=await uploadDirectMedia(id,user!.id,attachments);
  try{await sendDirectMessage(recipient.id,body,paths);}catch(e){await discardDirectMedia(paths);throw e;}
  if(currentId===selectedConversation.current){setContent('');setFiles([]);}nearBottom.current=true;if(!currentId)navigate(`/messages/${id}`);
  await Promise.all([client.invalidateQueries({queryKey:directKeys.inbox}),client.invalidateQueries({queryKey:directKeys.messages(id)}),client.invalidateQueries({queryKey:['direct-conversation',id]})]);
 });};
 const respond=(accept:boolean)=>void run(async()=>{await respondDirectRequest(conversationId!,accept);await Promise.all([client.invalidateQueries({queryKey:directKeys.inbox}),client.invalidateQueries({queryKey:['direct-conversation',conversationId]})]);if(!accept)navigate('/messages');});
 const openSettings=()=>{setSettings(true);setDetails(false);};
 const pinChat=(id:string,pinned:boolean)=>void run(async()=>{await setChatInboxPreference(id,'pins',!pinned);await client.invalidateQueries({queryKey:['chat-inbox-preferences',user?.id]});});
 const deleteChat=()=>{if(!deleteTarget||deleteTarget.id==='limeai')return;const target=deleteTarget;void run(async()=>{if(target.id.startsWith('friend:')){const friend=target.id.slice(7);let meta:Record<string,{assistantId?:string}>={};try{meta=JSON.parse(localStorage.getItem(`limeai:${user!.id}:session-meta`)??'{}')}catch{}const ids=(aiHistory.data??[]).filter(session=>meta[session.id]?.assistantId===friend).map(session=>session.id);if(ids.length){window.dispatchEvent(new CustomEvent(AI_CHAT_DELETED,{detail:{uid:user!.id,ids}}));const {error}=await supabase.from('chat_sessions').delete().eq('user_id',user!.id).in('id',ids);if(error)throw error;}await setChatInboxPreference(target.id,'hidden',true);await setChatInboxPreference(target.id,'pins',false);}else{await deleteDirectChat(target.id);}setDeleteTarget(null);if(conversationId===target.id)navigate('/messages');await Promise.all([client.invalidateQueries({queryKey:directKeys.inbox}),client.invalidateQueries({queryKey:['chat-inbox-preferences',user?.id]}),client.invalidateQueries({queryKey:['ai-inbox-history',user?.id]}),client.invalidateQueries({queryKey:directKeys.messages(target.id)})]);});};
 const cards=[...(showLimeAI?[{id:'limeai',peer:limeAI,preview:aiPreviews.limeai??'',unread:0,edit:undefined}]:[]),...visibleFriends.map(({friend,peer})=>({id:`friend:${friend.id}`,peer,preview:aiPreviews[friend.id]??'',unread:0,edit:()=>navigate(`/messages/${encodeURIComponent(`friend:${friend.id}`)}?action=friend`)})),...filtered.map(c=>({id:c.id,peer:c.peer,preview:c.status==='pending'?(c.initiatedBy===user?.id?'リクエスト送信済み':'メッセージリクエスト'):c.preview||(c.hasMedia?'画像':''),unread:c.unreadCount,updatedAt:c.updatedAt,edit:undefined}))].sort((a,b)=>Number(!!chatPreferences.data?.pins?.[b.id])-Number(!!chatPreferences.data?.pins?.[a.id]));
 return <div ref={workspace} className="dm-workspace" data-lime-dm data-dm-detail={!!conversationId||settings||undefined}>
  <section className="dm-inbox" aria-label="会話一覧">
   <DirectMessagePanelHeader className="dm-inbox-header" actions={<><DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="dm-filter">{filter==='all'?'すべて':filter==='unread'?'未読':'リクエスト'}<ChevronDown size={18}/></button></DropdownMenuTrigger><ChatMenuContent align="end" className="dm-menu">
    {(['all','unread','requests'] as const).map(value=><DropdownMenuItem key={value} onSelect={()=>{setFilter(value);setSettings(false);}}><MessageCircle size={19}/>{value==='all'?'すべて':value==='unread'?'未読':`リクエスト${requestCount?` (${requestCount})`:''}`}{filter===value&&<Check className="ml-auto" size={18}/>}</DropdownMenuItem>)}<DropdownMenuSeparator/><DropdownMenuItem onSelect={openSettings}><Settings size={19}/>設定</DropdownMenuItem><DropdownMenuItem onSelect={()=>void run(async()=>{await Promise.all((inbox.data??[]).filter(c=>c.unreadCount).map(async c=>{const rows=await getDirectMessages(c.id);if(rows[0])await readDirectConversation(c.id,rows[0].created_at);}));await client.invalidateQueries({queryKey:directKeys.inbox});})}><CheckCheck size={19}/>すべてを既読にする</DropdownMenuItem>
   </ChatMenuContent></DropdownMenu><button type="button" className="dm-icon-button dm-round" aria-label="新しいチャット" onClick={()=>{setError('');setNewChat(true);}}><MessageCirclePlus size={21}/></button></>}><h1>チャット</h1></DirectMessagePanelHeader>
   <label className="dm-search"><Search size={19}/><input aria-label="チャットを検索" placeholder="検索" value={search} onChange={e=>setSearch(e.target.value)}/></label>
   <div className="dm-conversations">
    {cards.map(card=><ConversationRow key={card.id} {...card} active={conversationId===card.id&&!settings} pinned={!!chatPreferences.data?.pins?.[card.id]} onOpen={()=>{setSettings(false);setDraftPeer(null);navigate(`/messages/${encodeURIComponent(card.id)}`)}} onPin={()=>pinChat(card.id,!!chatPreferences.data?.pins?.[card.id])} onEdit={card.edit} onDelete={card.id==='limeai'?undefined:()=>setDeleteTarget({id:card.id,name:card.peer.displayName})}/>)}
    {inbox.isPending?Array.from({length:4},(_,i)=><div className="dm-list-skeleton" key={i}><Skeleton className="h-12 w-12 shrink-0 rounded-full"/><Skeleton className="h-8 w-full rounded-lg"/></div>):inbox.isError?<p className="dm-status">チャットを取得できませんでした。<button onClick={()=>void inbox.refetch()}>再試行</button></p>:cards.length===0?<p className="dm-status">{filter==='requests'?'メッセージリクエストはありません':search?'該当するチャットはありません':'まだチャットはありません'}</p>:null}

   </div>
  </section>
  <section className="dm-thread" aria-label={settings?'チャット設定':'メッセージ'}>
   {isAI&&!settings?<Suspense fallback={<div className="dm-message-skeleton"><Skeleton className="h-10 w-40 rounded-3xl"/></div>}><LimeAIChat key={`${friendId??'limeai'}:${searchParams.get('action')??'chat'}`} friendId={friendId} onEditFriend={()=>navigate(`/messages/${encodeURIComponent(`friend:${friendId}`)}?action=friend`)} onFriendCreated={id=>navigate(`/messages/${encodeURIComponent(`friend:${id}`)}`)} embedded initialAction={searchParams.get('action')==='friend'?'friend':undefined} onBack={()=>navigate(searchParams.get('action')==='friend'?`/messages/${encodeURIComponent(conversationId!)}`:'/messages')}/></Suspense>:settings?<><DirectMessagePanelHeader back={()=>setSettings(false)}><h2>メッセージリクエスト</h2></DirectMessagePanelHeader><button type="button" className="dm-preference-row" onClick={()=>{setPreferenceDraft(preferences.data??'everyone');setPreferenceDialog(true);}} disabled={preferences.isPending||preferences.isError}><span>メッセージリクエストを許可</span><span>{preferences.data==='none'?'なし':'全員'}<MoreHorizontal size={18}/></span></button><p className="dm-settings-note">相互フォローしているユーザーは、この設定に関係なくメッセージを送信できます。</p>{preferences.isError&&<p className="dm-status">設定を取得できませんでした。</p>}</>:!peer&&!conversationId?<div className="dm-empty"><MessageCircle size={42}/><h2>メッセージを送る</h2><p>新しいチャットを始めたり、一覧から会話を選んだりできます。</p><button type="button" className="dm-primary" onClick={()=>setNewChat(true)}>新しいチャット</button></div>:conversation.isError||active?.status==='declined'?<><DirectMessagePanelHeader back={()=>navigate('/messages')}><h2>チャット</h2></DirectMessagePanelHeader><p className="dm-status">この会話を開けません。</p></>:<>
    <DirectMessagePanelHeader back={()=>navigate('/messages')} className="dm-thread-header" actions={<button type="button" className="dm-icon-button dm-round" aria-label="会話の詳細" onClick={()=>setDetails(true)}><MoreHorizontal size={23}/></button>}>
     {peer?<button type="button" className="dm-thread-peer" onClick={()=>setDetails(true)}><PeerAvatar peer={peer}/><PeerName peer={peer}/></button>:<Skeleton className="h-10 w-36 rounded-full"/>}
    </DirectMessagePanelHeader>
    <div className="dm-history" ref={scroller} onScroll={()=>{const el=scroller.current;if(el){nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<64;if(nearBottom.current){setNewMessageBelow(false);markRead();}}}}>
     <div ref={historyTop}/>{messages.isFetchingNextPage&&<div className="dm-status"><Loader2 className="animate-spin" size={18}/></div>}
     {!messages.hasNextPage&&peer&&<div className="dm-peer-intro"><PeerAvatar peer={peer}/><PeerName peer={peer}/><span>@{peer.username}</span><p>{new Date(peer.createdAt).toLocaleDateString('ja-JP',{year:'numeric',month:'long'})}からLimeNoteを利用しています</p><Link className="dm-profile-link" to={`/u/${peer.username}`}>プロフィールを表示</Link></div>}
     {messages.isPending?<div className="dm-message-skeleton"><Skeleton className="h-10 w-40 rounded-3xl"/><Skeleton className="ml-auto h-12 w-48 rounded-3xl"/></div>:messages.isError?<p className="dm-status">メッセージを取得できませんでした。<button onClick={()=>void messages.refetch()}>再試行</button></p>:chronological.map((m,i)=><div key={m.id} className="dm-message-group">
      {(i===0||new Date(m.created_at).toDateString()!==new Date(chronological[i-1].created_at).toDateString())&&<time className="dm-date" dateTime={m.created_at}>{new Date(m.created_at).toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric'})}</time>}
      <div className={`dm-message ${m.sender_id===user?.id?'is-own':''}`}><div className={`dm-bubble ${/^https?:\/\/[^\s]+$/.test(m.content.trim())?'has-link':''}`}>{m.mediaUrls.map((url,j)=><a key={url} href={url} target="_blank" rel="noopener noreferrer"><img src={url} alt={`添付画像${j+1}`} loading="lazy"/></a>)}{m.content&&<p>{messageText(m.content)}</p>}</div><time dateTime={m.created_at}>{new Date(m.created_at).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</time></div>
     </div>)}<div ref={bottom}/>
    </div>
    {newMessageBelow&&<button className="dm-jump" aria-label="最新のメッセージへ" onClick={()=>{nearBottom.current=true;bottom.current?.scrollIntoView({behavior:'smooth'});setNewMessageBelow(false);markRead();}}><ArrowDown size={20}/></button>}
    {incoming?<div className="dm-request-controls"><p>このユーザーからのメッセージリクエストを承認しますか？</p><div><button type="button" className="dm-secondary" disabled={busy} onClick={()=>respond(false)}>拒否</button><button type="button" className="dm-primary" disabled={busy} onClick={()=>respond(true)}>承認</button></div></div>:!canSend?<p className="dm-awaiting">リクエストを送信しました。承認されると続けてメッセージを送れます。</p>:<form className="dm-compose" onSubmit={e=>{e.preventDefault();send();}}>
     {active?.status==='pending'&&<p className="dm-request-hint">最初のメッセージはリクエストとして送信されます。</p>}
     {files.length>0&&<div className="dm-attachments">{previews.map((url,i)=><div key={url}><img src={url} alt={`添付予定の画像${i+1}`}/><button type="button" aria-label={`画像${i+1}を削除`} onClick={()=>setFiles(current=>current.filter((_,j)=>i!==j))}><X size={16}/></button></div>)}</div>}
     <div className="dm-compose-row"><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" multiple hidden onChange={e=>{const chosen=Array.from(e.target.files??[]);if(files.length+chosen.length>4){setError('画像は4枚まで添付できます');}else if(chosen.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10485760)){setError('画像はJPEG・PNG・WebP形式で、1枚10MB以下にしてください');}else{setError('');setFiles(current=>[...current,...chosen]);}e.target.value='';}}/><button type="button" className="dm-icon-button dm-round" aria-label="画像を添付" disabled={busy||files.length>=4} onClick={()=>fileInput.current?.click()}><Plus size={25}/></button><div className="dm-input"><textarea aria-label="メッセージ" placeholder="メッセージ" rows={1} maxLength={4000} value={content} disabled={busy} onChange={e=>setContent(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&window.matchMedia('(hover: hover) and (pointer: fine)').matches){e.preventDefault();send();}}}/><button type="submit" className="dm-icon-button" aria-label="送信" disabled={busy||(!content.trim()&&!files.length)}>{busy?<Loader2 className="animate-spin" size={20}/>:<Send size={21}/>}</button></div></div>
    </form>}
   </>}
   {error&&!newChat&&!preferenceDialog&&<p role="alert" className="dm-error">{error}</p>}
  </section>
  <Dialog open={newChat} onOpenChange={setNewChat}><DialogContent className="dm-dialog"><DialogTitle>新しいチャット</DialogTitle><button type="button" className="dm-conversation" onClick={()=>{setNewChat(false);setSettings(false);navigate('/messages/limeai');}}><PeerAvatar peer={limeAI}/><PeerName peer={limeAI}/></button><button type="button" className="dm-conversation" onClick={()=>{setNewChat(false);setSettings(false);navigate('/messages/limeai?action=friend');}}><Plus size={24}/><span>フレンドを作成</span></button>{friends.filter(({friend})=>chatPreferences.data?.hidden?.[`friend:${friend.id}`]).map(({friend,peer})=><button type="button" className="dm-conversation" key={friend.id} disabled={busy} onClick={()=>void run(async()=>{await setChatInboxPreference(`friend:${friend.id}`,'hidden',false);await client.invalidateQueries({queryKey:['chat-inbox-preferences',user?.id]});setNewChat(false);navigate(`/messages/${encodeURIComponent(`friend:${friend.id}`)}`);})}><PeerAvatar peer={peer}/><PeerName peer={peer}/></button>)}<label className="dm-search"><Search size={19}/><input autoFocus aria-label="ユーザーを検索" placeholder="名前またはユーザー名" value={peerSearch} onChange={e=>setPeerSearch(e.target.value)}/></label><div className="dm-peer-results">{peers.isFetching?<Skeleton className="h-12 w-full rounded-xl"/>:peers.isError?<p>ユーザーを検索できませんでした</p>:peers.data?.filter(p=>p.id!==user?.id).map(p=><button type="button" key={p.id} className="dm-conversation" disabled={busy} onClick={()=>pickPeer(p)}><PeerAvatar peer={p}/><span className="dm-conversation-text"><PeerName peer={p}/><span className="dm-preview">@{p.username}</span></span></button>)}</div>{error&&<p role="alert" className="dm-error">{error}</p>}</DialogContent></Dialog>
  <Dialog open={details} onOpenChange={setDetails}><DialogContent className="dm-dialog dm-details"><DialogTitle className="sr-only">会話の詳細</DialogTitle><DialogDescription className="sr-only">チャット相手のプロフィールと会話の状態</DialogDescription>{peer&&<><PeerAvatar peer={peer}/><PeerName peer={peer}/><p className="dm-muted">@{peer.username}</p><Link className="dm-profile-link" to={`/u/${peer.username}`}>プロフィールを表示</Link><p className="dm-muted">{active?.status==='pending'?'メッセージリクエスト':''}</p></>}</DialogContent></Dialog>
  <Dialog open={preferenceDialog} onOpenChange={setPreferenceDialog}><DialogContent className="dm-dialog"><DialogTitle>メッセージリクエストを許可</DialogTitle><DialogDescription>相互フォローしているユーザーは、どちらの設定でも送信できます。</DialogDescription><fieldset className="dm-radio-list"><legend className="sr-only">リクエストの受信範囲</legend>{(['none','everyone'] as const).map(value=><label key={value}><Lock size={21}/><span>{value==='none'?'なし':'全員'}</span><input type="radio" name="dm-requests" value={value} checked={preferenceDraft===value} onChange={()=>setPreferenceDraft(value)}/></label>)}</fieldset>{error&&<p role="alert" className="dm-error">{error}</p>}<button className="dm-secondary" disabled={busy} onClick={()=>setPreferenceDialog(false)}>キャンセル</button><button className="dm-primary" disabled={busy} onClick={()=>void run(async()=>{await setDirectPreferences(preferenceDraft);await client.invalidateQueries({queryKey:directKeys.preferences});setPreferenceDialog(false);})}>確認する</button></DialogContent></Dialog>
  <Dialog open={!!deleteTarget} onOpenChange={open=>{if(!open&&!busy)setDeleteTarget(null)}}><DialogContent className="dm-dialog"><DialogTitle>チャットを削除</DialogTitle><DialogDescription>{deleteTarget?.name}とのチャットを自分の画面から削除します。相手の画面には会話が残ります。{deleteTarget?.id.startsWith('friend:')&&'フレンド自体は削除されません。'}</DialogDescription>{error&&<p className="dm-error">{error}</p>}<div className="dm-delete-controls"><button className="dm-secondary" disabled={busy} onClick={()=>setDeleteTarget(null)}>キャンセル</button><button className="dm-primary" disabled={busy} onClick={deleteChat}>削除する</button></div></DialogContent></Dialog>
 </div>;
}
