import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',p='33333333-3333-4333-8333-333333333333',c='44444444-4444-4444-8444-444444444444';
await db.exec(`create role authenticated;create role anon;create role service_role;create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.viewer',true),'')::uuid$$;
create table profiles(id uuid primary key,username text,display_name text,avatar_url text,is_official boolean);
create table profile_private_settings(user_id uuid primary key references profiles(id),bot_prompt text);
create table posts(id uuid primary key,user_id uuid references profiles(id),content text,image_urls text[],visibility text);
create table comments(id uuid primary key,post_id uuid references posts(id),user_id uuid references profiles(id),parent_comment_id uuid references comments(id),content text,image_urls text[]);
create table likes(user_id uuid,post_id uuid);create table reposts(user_id uuid,post_id uuid);
create table post_reactions(user_id uuid,post_id uuid,emoji text);
create table comment_likes(user_id uuid,comment_id uuid);create table reply_reposts(user_id uuid,comment_id uuid);create table comment_reactions(user_id uuid,comment_id uuid,emoji text);
create table follows(follower_id uuid,followee_id uuid);create table mentions(id uuid default gen_random_uuid(),post_id uuid,mentioned_user_id uuid);
create table notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id),actor_id uuid not null references profiles(id),post_id uuid references posts(id),type text not null,is_read boolean default false,created_at timestamptz default now(),actor_name text,actor_avatar_url text,content_preview text);
create table post_notification_subscriptions(id uuid primary key default gen_random_uuid(),subscriber_id uuid not null references profiles(id),target_user_id uuid not null references profiles(id),created_at timestamptz not null default now(),unique(subscriber_id,target_user_id),check(subscriber_id<>target_user_id));
insert into profiles values('${a}','alice','Alice',null,true),('${b}','bob','Bob',null,false);
insert into posts values('${p}','${a}','original',array['image.jpg'],'public');
insert into profile_private_settings values('${a}','preserve me');
`);
const tableCountBefore=(await db.query("select count(*) as count from information_schema.tables where table_schema='public'")).rows[0].count;
await db.exec(await readFile(new URL('../supabase/migrations/20261008210000_notification_preferences_and_activity.sql',import.meta.url),'utf8'));
await db.exec(`create trigger mention_notify after insert on mentions for each row execute function create_mention_notification();create trigger new_post_notify after insert on posts for each row execute function notify_post_subscribers();`);
const count=async(type)=>Number((await db.query('select count(*) as count from notifications where type=$1',[type])).rows[0].count);
await db.exec(`insert into comments values('${c}','${p}','${b}',null,'reply',array['reply.jpg']);insert into likes values('${b}','${p}');insert into reposts values('${b}','${p}');insert into post_reactions values('${b}','${p}','❤️');insert into follows values('${b}','${a}');insert into mentions(post_id,mentioned_user_id) values('${p}','${b}');`);
for(const type of ['reply','like','repost','reaction','follow','mention'])assert.equal(await count(type),1,type);
assert.deepEqual((await db.query("select image_urls from notifications where type='like'")).rows[0].image_urls,['image.jpg']);
await db.exec(`insert into likes values('${a}','${p}'),('${b}','${p}');`);assert.equal(await count('like'),1,'self and duplicate events suppressed');
await db.exec(`insert into comment_likes values('${a}','${c}');insert into reply_reposts values('${a}','${c}');insert into comment_reactions values('${a}','${c}','👍');`);
for(const type of ['like','repost','reaction'])assert.equal(await count(type),2,'reply activity '+type);
await db.query("select set_config('test.viewer',$1,false)",[a]);
await db.exec("set role authenticated; select set_notification_preference('like',false);reset role;");
assert.equal((await db.query('select bot_prompt from profile_private_settings where user_id=$1',[a])).rows[0].bot_prompt,'preserve me');
await db.exec(`delete from notifications where type='like' and user_id='${a}';insert into likes values('${b}','${p}');`);assert.equal(await count('like'),1,'disabled kind not created');
await db.exec(`insert into post_notification_subscriptions(subscriber_id,target_user_id) values('${b}','${a}');insert into posts values('55555555-5555-4555-8555-555555555555','${a}','new','{}','public');insert into posts values('66666666-6666-4666-8666-666666666666','${a}','private','{}','following');`);assert.equal(await count('new_post'),1,'private posts not pushed');
const subscription=(await db.query(`insert into post_notification_subscriptions(subscriber_id,provider,external_actor) values('${a}','bluesky','alice.bsky.social') returning id,created_at`)).rows[0];
const now=new Date().toISOString();const events=[{id:'bsky:at://did:plc:test/app.bsky.feed.post/new',created_at:now,name:'External',avatar:'',content:'new external',images:[]},{id:'bsky:old',created_at:'2020-01-01',content:'old',images:[]}];
await db.query('select record_external_post_notifications($1,$2,$3)',[subscription.id,JSON.stringify(events),JSON.stringify({seen:[events[0].id]})]);
assert.equal(await count('new_post'),2,'new external event only');
await db.query('select record_external_post_notifications($1,$2,$3)',[subscription.id,JSON.stringify(events),'{}']);assert.equal(await count('new_post'),2,'worker deduplication');
await db.exec('set role authenticated;');await assert.rejects(db.query('select record_external_post_notifications($1,$2,$3)',[subscription.id,'[]','{}']));await db.exec('reset role;');
await db.query("select set_config('test.viewer',$1,false)",[a]);await db.exec("set role authenticated;select set_notification_preference('new_post',false);reset role;");
await db.query('select record_external_post_notifications($1,$2,$3)',[subscription.id,JSON.stringify([{...events[0],id:'bsky:disabled'}]),'{}']);assert.equal(await count('new_post'),2,'external preference respected');
// Exercise retention with real RLS and read-only notification update privileges.
await db.exec(`create schema vault;create table vault.decrypted_secrets(name text,decrypted_secret text);create schema net;
create function net.http_post(url text,headers jsonb,body jsonb,timeout_milliseconds integer) returns bigint language sql as $$ select 1::bigint $$;
insert into notifications(user_id,actor_id,type,created_at) values('${a}','${b}','follow','2026-05-01');
alter table notifications enable row level security;create policy own_notifications on notifications for select to authenticated using(user_id=auth.uid());create policy own_notifications_update on notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());grant select on notifications to authenticated;
`);
await db.exec(await readFile(new URL('../supabase/migrations/20261008213000_notification_delivery_and_expiry.sql',import.meta.url),'utf8'));
assert.equal(Number((await db.query("select count(*) as count from notifications where created_at='2026-05-01'")).rows[0].count),0,'old May notifications deleted');
await db.exec(`update notifications set expires_at=now()-interval '1 second' where user_id='${a}';set role authenticated;`);
assert.equal(Number((await db.query('select count(*) as count from notifications')).rows[0].count),0,'expired notifications excluded from badge count by RLS');
await assert.rejects(db.exec('select public.expire_notifications()'));await db.exec('reset role;');
await db.query("select set_config('test.viewer',$1,false)",[b]);await db.exec('set role authenticated;');
await db.exec("update notifications set is_read=true where is_read=false");
await assert.rejects(db.exec("update notifications set actor_name='tampered'"));await db.exec('reset role;');
await db.exec(await readFile(new URL('../supabase/migrations/20261008220000_external_notification_worker_permissions.sql',import.meta.url),'utf8'));
await db.exec('set role service_role;');
assert.equal((await db.query('select count(*) as count from post_notification_subscriptions')).rows[0].count,2,'server can read subscriptions');
await db.exec('update post_notification_subscriptions set last_checked_at=now()');
await assert.rejects(db.exec("update post_notification_subscriptions set external_actor='tampered'"));
await db.exec('reset role;');
await db.exec(await readFile(new URL('../supabase/migrations/20261008223000_notification_event_delivery.sql',import.meta.url),'utf8'));
await db.exec(`insert into notifications(user_id,actor_id,type) values('${b}','${a}','follow');`);
assert.equal(Number((await db.query('select count(*) as count from notifications where expires_at<=now()')).rows[0].count),0,'expired rows removed on notification insert without cron');
assert.equal((await db.query('select count(*) as count from information_schema.tables where table_schema=\'public\'')).rows[0].count,tableCountBefore,'no new app tables');
console.log('Notifications DB: all activity kinds, replies, self/duplicate suppression, private settings, external delivery/age/deduplication, disabled settings and worker permissions passed; no new tables');await db.close();
