name: 6-hour-news-cron
on:
  schedule:
    - cron: '17 */6 * * *' # 0分を避けて「17分」に変更。これでGitHubの目につきやすくなる
  workflow_dispatch:

jobs:
  run-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Function
        run: |
          curl -X POST "https://wrxaayteittkjoblgauk.supabase.co/functions/v1/generate-news" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
